# Generated by Django 4.1.5 on 2023-02-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('farm_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('longtude', models.CharField(blank=True, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_farms',
            },
        ),
    ]
