# Generated by Django 4.1.5 on 2023-02-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_userdevice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='switch_status',
            field=models.BooleanField(default=False),
        ),
    ]
